name: Build
on:
    push:
      branches:
      - '**'
      tags:
        - 'v*'

permissions:
  contents: read
  packages: write

jobs:  
  ko-build:
    if: github.event_name == 'push' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    uses: metraction/github-actions/.github/workflows/ko-build.yaml@incremental
    secrets: inherit
    
  push-helm-chart:
    uses: metraction/github-actions/.github/workflows/helm-push.yaml@incremental
    needs: [ko-build]
    with:
      chart_dir: helm/dora-badge
      chart_name: dora-badge
      destination: .
      registry: oci://ghcr.io/metraction/charts
    secrets: inherit