name: Build with ko

on:
  push:
    branches: 
    - main
    - DB-12/*
    tags:
    - 'v*'

  pull_request:
    branches: [ main ]

jobs:
  ko-build:
    uses: metraction/github-actions/.github/workflows/ko-build.yaml@main
    secrets: inherit
        