name: Build with ko

on:
  push:
    branches: 
    - main
  pull_request:
    branches: [ main ]

jobs:
  ko-build:
    uses: Tiktai/helm-publish/.github/workflows/ko-build.yaml@main
    secrets: inherit
        