name: Build with ko

on:
  push:
    branches: 
    - main
  pull_request:
    branches: [ main ]

  permissions:
    contents: read
    packages: write
    attestations: write
    id-token: write

jobs:
  ko-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ko-build/setup-ko@v0.9
      - name: Build image with ko
        run: |
          ko build --sbom=none --platform=linux/amd64 --tags=latest
